[package]
name = "indiscriminant"
version = "0.1.0"
edition = "2021"

[dependencies]
indiscriminant_impl_byte_str = { path = "impl_byte_str", version = "0.1.0" }
indiscriminant_impl_str = { path = "impl_str", version = "0.1.0" }
indiscriminant_impl_bits = { path = "impl_bits", version = "0.1.0" }