[package]
name = "indiscriminant_impl_bits"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.76"
quote = "1.0.9"
indiscriminant_impl_str = { path = "../impl_str", version = "0.1.0" }