[package]
name = "no_discrimination_impl_bits"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.76"
quote = "1.0.9"
no_discrimination_impl_str = { path = "../impl_str", version = "0.1.0" }